# Site settings
title: 子遥博客
author: 子遥
author_info: just laravel
email: yangyaohappy@outlook.com
description: 子遥的个人网站
baseurl: "/blog"
#url: "http://blog.itxti.net"
# Converter settings
# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'

# Social account
# twitter:  username
weibo:    yangyaohappy
github:   yangyao
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID

